server:
  port: 18089  #服务端口
  host: 192.168.150.1 #监听所有网络接口
  logger:
    file: logs/app.log
    level: DEBUG # 日志级别: CRITICAL, ERROR, WARNING, INFO, DEBUG

db:
  url: "${AGENT_CENTER_DB_URL}"
  pool_size: 10           # 连接池大小
  max_overflow: 20        # 超出连接池的最大连接数
  pool_timeout: 30        # 池中无连接时的等待时间
  pool_recycle: 1800      # 连接回收时间（秒）
  echo: True

redis:
  host: "${AGENT_CENTER_REDIS_HOST}"
  port: "${AGENT_CENTER_REDIS_PORT}"
  password: "${AGENT_CENTER_REDIS_PASSWORD}"

jwt:
  private_key: "${AGENT_CENTER_JWT_PRIVATE_KEY}"
  public_key: "${AGENT_CENTER_JWT_PUBLIC_KEY}"
  expire_hours: 720 #token有效期，单位小时# 控制台输出 SQL

ai:
  "1001":
    session:
      title: Hello，我是天机AI助理
      describe: 我是由天机学堂倾力打造的智能助理，我不仅能推荐课程、答疑解惑，还能为您激发创意、畅聊心事。
      examples:
        - title: "课程推荐"
          describe: "能帮我推荐一个合适的课吗？"
        - title: "课程推荐"
          describe: "最近有什么新课吗？"
        - title: "课程推荐"
          describe: "如何选择适合我的课程？"
        - title: "课程推荐"
          describe: "有哪些热门课程推荐？"
        - title: "课程购买"
          describe: "我想要购买《Java进阶编程实战》"
        - title: "课程购买"
          describe: "我想要报名《Java高级架构与微服务》"
        - title: "课程购买"
          describe: "《Java进阶编程实战》的课程价格是多少？"
        - title: "课程购买"
          describe: "《Java高级架构与微服务》的课程价格是多少？"
        - title: "课程介绍"
          describe: "请帮我介绍一下《互联网产品运营实战》"
        - title: "课程介绍"
          describe: "《Java大数据处理与分析》这门课一共有多少节？"
        - title: "课程介绍"
          describe: "《Java高级架构与微服务》能学到什么内容？"
        - title: "课程介绍"
          describe: "《互联网产品运营实战》适合我学习吗？"
        - title: "知识讲解"
          describe: "面向对象的三大特征是什么？"
        - title: "知识讲解"
          describe: "ArrayList和LinkedList有何区别？"
        - title: "知识讲解"
          describe: "Java多线程怎么实现？"
        - title: "知识讲解"
          describe: "Spring Boot和SSM有什么区别？"
        - title: "知识讲解"
          describe: "列表和元组有什么区别？"
        - title: "知识讲解"
          describe: " Python如何管理内存？"
        - title: "知识讲解"
          describe: " 装饰器的作用是什么？"
        - title: "知识讲解"
          describe: "多线程为什么有GIL限制？"
  openai:
    model: qwen3.8-max
    api-key: "${AGENT_CENTER_AI_API_KEY}"
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    temperature: 0.8
    timeout: 30
  agent:
    checkpointer:
      postgres:
        min: 5 # 最小连接数
        max: 10 # 最大连接数
        url: "${AGENT_CENTER_POSTGRES_URL}"

nacos:
  server-addr: "${AGENT_CENTER_NACOS_SERVER_ADDR}" # nacos注册中心
  username: "${AGENT_CENTER_NACOS_USERNAME}"
  password: "${AGENT_CENTER_NACOS_PASSWORD}"
  config:
    namespace: public
    group: DEFAULT_GROUP
  discovery:
    name: agent-center
    namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
    ip: "${AGENT_CENTER_NACOS_DISCOVERY_IP}"
