name: ac_env_3135
channels:
  - defaults
dependencies:
  - python=3.13.5
  - pip=25.3
  - pip:
      - fastapi==0.122.0
      - httpx==0.28.1
      - langchain==1.1.0
      - langchain-core==1.1.0
      - langchain-openai==1.1.0
      - langgraph==1.0.4
      - langgraph-checkpoint-postgres==3.0.1
      - nacos-sdk-python==2.0.9
      - psycopg==3.2.13
      - psycopg-binary==3.2.13
      - psycopg-pool==3.2.8
      - pydantic==2.12.5
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - uvicorn==0.38.0
